"""Registry of all graph types and their algorithm options."""

GRAPH_TYPES = [
    "apex",
    "at_free",
    "biconnected",
    "biconvex_bipartite",
    "bipartite",
    "bipartite_permutation",
    "block",
    "bull_free",
    "cactus",
    "caterpillar",
    "chain",
    "chordal",
    "chordal_bipartite",
    "circle",
    "circular_arc",
    "claw_free",
    "cluster",
    "co_chordal",
    "co_comparability",
    "co_interval",
    "cochain",
    "cograph",
    "comparability",
    "convex_bipartite",
    "cubic",
    "cubic_planar",
    "diamond_free",
    "digraph",
    "distance_hereditary",
    "eulerian",
    "even_hole_free",
    "five_leaf_power",
    "forest",
    "four_leaf_power",
    "fullerene",
    "gem_free",
    "halin",
    "interval",
    "kregular",
    "ktree",
    "laman",
    "line_graph",
    "maximal_planar",
    "meyniel",
    "odd_hole_free",
    "outer_planar",
    "p5_free",
    "parity",
    "perfect",
    "permutation",
    "planar",
    "polyhedral",
    "poset",
    "proper_chordal",
    "proper_circular_arc",
    "proper_interval",
    "ptolemaic",
    "quasi_threshold",
    "self_complementary",
    "series_parallel",
    "simple_quadrangulation",
    "snark",
    "split",
    "strongly_chordal",
    "strongly_regular",
    "three_leaf_power",
    "threshold",
    "tournament",
    "trapezoid",
    "tree",
    "triangle_free",
    "triconnected",
    "trivially_perfect",
    "unicyclic",
    "unit_interval",
    "weakly_chordal",
]

ALGORITHMS = {
    "apex": ["vertex_deletion"],
    "at_free": ["brute_force"],
    "biconnected": ["dfs", "block_cut_tree"],
    "biconvex_bipartite": ["brute_force", "c1p"],
    "bipartite": ["bfs"],
    "bipartite_permutation": ["bipartite_and_permutation"],
    "block": ["dfs", "chordal_diamond_free", "block_cut_tree"],
    "bull_free": ["triangle_search", "brute"],
    "cactus": ["dfs", "block_cut_tree"],
    "caterpillar": ["leaf_removal"],
    "chain": ["neighborhood_inclusion", "degree_sort"],
    "chordal": ["mcs_peo", "bucket_mcs_peo", "lexbfs_peo"],
    "chordal_bipartite": ["cycle_check", "bisimplicial", "fast_bisimplicial"],
    "circle": ["naji_system", "dow_backtracking"],
    "circular_arc": ["mcconnell", "backtracking"],
    "claw_free": ["triple_loop", "edge_count"],
    "cluster": ["component_clique"],
    "co_chordal": ["complement"],
    "co_comparability": ["complement"],
    "co_interval": ["complement"],
    "cochain": ["complement", "direct"],
    "cograph": ["cotree", "partition_refinement", "modular"],
    "comparability": ["transitive_orientation"],
    "convex_bipartite": ["brute_force", "c1p"],
    "cubic": ["degree_check"],
    "cubic_planar": ["cubic_and_planar"],
    "diamond_free": ["brute", "edge_pair"],
    "digraph": ["validity_check"],
    "distance_hereditary": ["hashmap_twins", "sorted_twins", "hash_twins", "split_decomposition"],
    "eulerian": ["degree_check"],
    "even_hole_free": [],
    "five_leaf_power": [],
    "forest": ["bfs"],
    "four_leaf_power": [],
    "fullerene": ["face_check"],
    "gem_free": ["neighbor_p4_search", "brute"],
    "halin": ["face_check"],
    "interval": ["backtracking", "at_free", "pq_tree"],
    "kregular": ["degree_check"],
    "ktree": ["simplicial_removal"],
    "laman": ["pebble_game"],
    "line_graph": ["brute", "krausz"],
    "maximal_planar": ["planar_edge_count"],
    "meyniel": ["direct_check"],
    "odd_hole_free": [],
    "outer_planar": ["minor_check", "augmented_planarity"],
    "p5_free": ["path_search", "brute"],
    "parity": ["direct_check"],
    "perfect": [],
    "permutation": ["backtracking", "class_based"],
    "planar": ["left_right", "minor_check"],
    "polyhedral": ["steinitz"],
    "poset": ["dag_and_reduction"],
    "proper_chordal": [],
    "proper_circular_arc": [],
    "proper_interval": ["triple_loop_claw_check", "fast_claw_check"],
    "ptolemaic": ["dh_hashmap", "dh_sorted"],
    "quasi_threshold": ["dfs"],
    "self_complementary": ["isomorphism_check"],
    "series_parallel": ["minor_check", "queue_reduction"],
    "simple_quadrangulation": ["combined"],
    "snark": ["combined"],
    "split": ["degree_sequence", "hammer_simeone"],
    "strongly_chordal": ["strong_elimination", "peo_matrix", "mcs_seo", "farber_seo"],
    "strongly_regular": ["parameter_check"],
    "three_leaf_power": [],
    "threshold": ["degree_sequence", "degree_sequence_fast"],
    "tournament": ["arc_check"],
    "trapezoid": ["chain_cover"],
    "tree": ["bfs"],
    "triangle_free": ["edge_pair", "brute"],
    "triconnected": ["naive"],
    "trivially_perfect": ["dfs"],
    "unicyclic": ["bfs"],
    "unit_interval": ["proper_interval"],
    "weakly_chordal": ["co_chordal_bipartite", "complement_bfs"],
}

# Human-readable names for documentation
DISPLAY_NAMES = {
    "apex": "apex",
    "at_free": "AT-free",
    "biconnected": "biconnected",
    "biconnected_unlabeled": "biconnected",
    "biconvex_bipartite": "biconvex bipartite",
    "bipartite": "bipartite",
    "bipartite_permutation": "bipartite permutation",
    "bipartite_unlabeled": "bipartite",
    "block": "block",
    "bull_free": "bull-free",
    "cactus": "cactus",
    "caterpillar": "caterpillar",
    "chain": "chain",
    "chordal": "chordal",
    "chordal_bipartite": "chordal bipartite",
    "chordal_unlabeled": "chordal",
    "circle": "circle",
    "circle_unlabeled": "circle",
    "circular_arc": "circular-arc",
    "claw_free": "claw-free",
    "cluster": "cluster",
    "cluster_unlabeled": "cluster",
    "co_chordal": "co-chordal",
    "co_chordal_unlabeled": "co-chordal",
    "co_comparability": "co-comparability",
    "co_interval": "co-interval",
    "co_interval_unlabeled": "co-interval",
    "cochain": "co-chain",
    "cograph": "cograph",
    "cograph_unlabeled": "cograph",
    "comparability": "comparability",
    "convex_bipartite": "convex bipartite",
    "cubic": "cubic",
    "cubic_unlabeled": "cubic",
    "cubic_planar": "cubic planar",
    "diamond_free": "diamond-free",
    "digraph": "digraph (directed input)",
    "distance_hereditary": "distance-hereditary",
    "distance_hereditary_unlabeled": "distance-hereditary",
    "eulerian": "Eulerian",
    "eulerian_unlabeled": "Eulerian",
    "even_hole_free": "even-hole-free",
    "five_leaf_power": "five-leaf power",
    "forest": "forest",
    "four_leaf_power": "four-leaf power",
    "fullerene": "fullerene",
    "gem_free": "gem-free",
    "halin": "Halin",
    "interval": "interval",
    "interval_unlabeled": "interval",
    "kregular": "k-regular",
    "ktree": "k-tree",
    "laman": "Laman",
    "line_graph": "line graph",
    "maximal_planar": "maximal planar",
    "maximal_planar_unlabeled": "maximal planar",
    "meyniel": "Meyniel",
    "odd_hole_free": "odd-hole-free",
    "outer_planar": "outerplanar",
    "outer_planar_unlabeled": "outerplanar",
    "p5_free": "P5-free",
    "parity": "parity",
    "perfect": "perfect",
    "permutation": "permutation",
    "permutation_unlabeled": "permutation",
    "planar": "planar",
    "planar_unlabeled": "planar",
    "polyhedral": "polyhedral",
    "poset": "poset Hasse diagram (directed input)",
    "proper_chordal": "proper chordal",
    "proper_circular_arc": "proper circular-arc",
    "proper_interval": "proper interval",
    "proper_interval_unlabeled": "proper interval",
    "ptolemaic": "Ptolemaic",
    "ptolemaic_unlabeled": "Ptolemaic",
    "quasi_threshold": "quasi-threshold",
    "self_complementary": "self-complementary",
    "self_complementary_unlabeled": "self-complementary",
    "series_parallel": "series-parallel",
    "simple_quadrangulation": "simple quadrangulation",
    "snark": "snark",
    "split": "split",
    "split_unlabeled": "split",
    "strongly_chordal": "strongly chordal",
    "strongly_regular": "strongly regular",
    "three_leaf_power": "three-leaf power",
    "three_leaf_power_unlabeled": "three-leaf power",
    "threshold": "threshold",
    "tournament": "tournament (directed input)",
    "trapezoid": "trapezoid",
    "tree": "tree",
    "triangle_free": "triangle-free",
    "triangle_free_unlabeled": "triangle-free",
    "triconnected": "triconnected",
    "trivially_perfect": "trivially perfect",
    "trivially_perfect_unlabeled": "trivially perfect",
    "unicyclic": "unicyclic",
    "unit_interval": "unit interval",
    "weakly_chordal": "weakly chordal",
}
