"""Registry of all graph types and their algorithm options."""

GRAPH_TYPES = [
    "at_free",
    "bipartite",
    "bipartite_permutation",
    "block",
    "cactus",
    "chain",
    "chordal",
    "chordal_bipartite",
    "circular_arc",
    "co_chordal",
    "co_comparability",
    "co_interval",
    "cochain",
    "cograph",
    "comparability",
    "distance_hereditary",
    "interval",
    "outer_planar",
    "permutation",
    "planar",
    "proper_interval",
    "ptolemaic",
    "quasi_threshold",
    "series_parallel",
    "split",
    "strongly_chordal",
    "threshold",
    "trivially_perfect",
    "unit_interval",
    "weakly_chordal",
]

ALGORITHMS = {
    "at_free": ["brute_force"],
    "bipartite": ["bfs"],
    "bipartite_permutation": ["chain_both_sides"],
    "block": ["dfs"],
    "cactus": ["dfs"],
    "chain": ["neighborhood_inclusion", "degree_sort"],
    "chordal": ["mcs_peo", "bucket_mcs_peo"],
    "chordal_bipartite": ["cycle_check", "bisimplicial", "fast_bisimplicial"],
    "circular_arc": ["mcconnell", "backtracking"],
    "co_chordal": ["complement"],
    "co_comparability": ["complement"],
    "co_interval": ["complement"],
    "cochain": ["complement", "direct"],
    "cograph": ["cotree", "partition_refinement"],
    "comparability": ["transitive_orientation"],
    "distance_hereditary": ["hashmap_twins", "sorted_twins", "hash_twins"],
    "interval": ["backtracking", "at_free"],
    "outer_planar": ["minor_check"],
    "permutation": ["backtracking", "class_based"],
    "planar": ["minor_check"],
    "proper_interval": ["pq_tree", "fast_claw_check"],
    "ptolemaic": ["dh_hashmap", "dh_sorted"],
    "quasi_threshold": ["dfs"],
    "series_parallel": ["minor_check", "queue_reduction"],
    "split": ["degree_sequence", "hammer_simeone"],
    "strongly_chordal": ["strong_elimination", "peo_matrix"],
    "threshold": ["degree_sequence", "degree_sequence_fast"],
    "trivially_perfect": ["dfs"],
    "unit_interval": ["proper_interval"],
    "weakly_chordal": ["co_chordal_bipartite", "complement_bfs"],
}

# Human-readable names for documentation
DISPLAY_NAMES = {
    "at_free": "AT-free",
    "bipartite": "bipartite",
    "bipartite_permutation": "bipartite permutation",
    "block": "block",
    "cactus": "cactus",
    "chain": "chain",
    "chordal": "chordal",
    "chordal_bipartite": "chordal bipartite",
    "circular_arc": "circular-arc",
    "co_chordal": "co-chordal",
    "co_comparability": "co-comparability",
    "co_interval": "co-interval",
    "cochain": "co-chain",
    "cograph": "cograph",
    "comparability": "comparability",
    "distance_hereditary": "distance-hereditary",
    "interval": "interval",
    "outer_planar": "outerplanar",
    "permutation": "permutation",
    "planar": "planar",
    "proper_interval": "proper interval",
    "ptolemaic": "Ptolemaic",
    "quasi_threshold": "quasi-threshold",
    "series_parallel": "series-parallel",
    "split": "split",
    "strongly_chordal": "strongly chordal",
    "threshold": "threshold",
    "trivially_perfect": "trivially perfect",
    "unit_interval": "unit interval",
    "weakly_chordal": "weakly chordal",
}
