"""Registry of all graph types and their algorithm options."""

GRAPH_TYPES = [
    "at_free",
    "biconvex_bipartite",
    "bipartite",
    "bipartite_permutation",
    "block",
    "cactus",
    "chain",
    "chordal",
    "chordal_bipartite",
    "circular_arc",
    "claw_free",
    "co_chordal",
    "co_comparability",
    "co_interval",
    "cochain",
    "cograph",
    "comparability",
    "convex_bipartite",
    "diamond_free",
    "distance_hereditary",
    "interval",
    "line_graph",
    "outer_planar",
    "perfect",
    "permutation",
    "planar",
    "proper_interval",
    "ptolemaic",
    "quasi_threshold",
    "series_parallel",
    "split",
    "strongly_chordal",
    "three_leaf_power",
    "threshold",
    "trapezoid",
    "trivially_perfect",
    "unit_interval",
    "weakly_chordal",
]

ALGORITHMS = {
    "at_free": ["brute_force"],
    "biconvex_bipartite": ["brute_force", "c1p"],
    "bipartite": ["bfs"],
    "bipartite_permutation": ["chain_both_sides"],
    "block": ["dfs", "chordal_diamond_free"],
    "cactus": ["dfs"],
    "chain": ["neighborhood_inclusion", "degree_sort"],
    "chordal": ["mcs_peo", "bucket_mcs_peo", "lexbfs_peo"],
    "chordal_bipartite": ["cycle_check", "bisimplicial", "fast_bisimplicial"],
    "circular_arc": ["mcconnell", "backtracking"],
    "claw_free": ["triple_loop", "edge_count"],
    "co_chordal": ["complement"],
    "co_comparability": ["complement"],
    "co_interval": ["complement"],
    "cochain": ["complement", "direct"],
    "cograph": ["cotree", "partition_refinement"],
    "comparability": ["transitive_orientation"],
    "convex_bipartite": ["brute_force", "c1p"],
    "diamond_free": ["brute", "edge_pair"],
    "distance_hereditary": ["hashmap_twins", "sorted_twins", "hash_twins"],
    "interval": ["backtracking", "at_free"],
    "line_graph": ["brute", "krausz"],
    "outer_planar": ["minor_check", "augmented_planarity"],
    "perfect": [],
    "permutation": ["backtracking", "class_based"],
    "planar": ["minor_check"],
    "proper_interval": ["pq_tree", "fast_claw_check"],
    "ptolemaic": ["dh_hashmap", "dh_sorted"],
    "quasi_threshold": ["dfs"],
    "series_parallel": ["minor_check", "queue_reduction"],
    "split": ["degree_sequence", "hammer_simeone"],
    "strongly_chordal": ["strong_elimination", "peo_matrix", "mcs_seo"],
    "three_leaf_power": [],
    "threshold": ["degree_sequence", "degree_sequence_fast"],
    "trapezoid": ["chain_cover"],
    "trivially_perfect": ["dfs"],
    "unit_interval": ["proper_interval"],
    "weakly_chordal": ["co_chordal_bipartite", "complement_bfs"],
}

# Human-readable names for documentation
DISPLAY_NAMES = {
    "at_free": "AT-free",
    "biconvex_bipartite": "biconvex bipartite",
    "bipartite": "bipartite",
    "bipartite_permutation": "bipartite permutation",
    "block": "block",
    "cactus": "cactus",
    "chain": "chain",
    "chordal": "chordal",
    "chordal_bipartite": "chordal bipartite",
    "circular_arc": "circular-arc",
    "claw_free": "claw-free",
    "co_chordal": "co-chordal",
    "co_comparability": "co-comparability",
    "co_interval": "co-interval",
    "cochain": "co-chain",
    "cograph": "cograph",
    "comparability": "comparability",
    "convex_bipartite": "convex bipartite",
    "diamond_free": "diamond-free",
    "distance_hereditary": "distance-hereditary",
    "interval": "interval",
    "line_graph": "line graph",
    "outer_planar": "outerplanar",
    "perfect": "perfect",
    "permutation": "permutation",
    "planar": "planar",
    "proper_interval": "proper interval",
    "ptolemaic": "Ptolemaic",
    "quasi_threshold": "quasi-threshold",
    "series_parallel": "series-parallel",
    "split": "split",
    "strongly_chordal": "strongly chordal",
    "three_leaf_power": "three-leaf power",
    "threshold": "threshold",
    "trapezoid": "trapezoid",
    "trivially_perfect": "trivially perfect",
    "unit_interval": "unit interval",
    "weakly_chordal": "weakly chordal",
}
